;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	Buffer-menu-backup-unmark
	Buffer-menu-this-window
	company-complete
	eval-and-replace
	helm-M-x
	org-force-cycle-archived
	))

(setq mc/cmds-to-run-once
      '(
	end-of-buffer
	viper-command-argument
	))
